name: Build
description: Build application with Maven and create a new Docker image
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build package with maven
      run: mvn -B package -DskipTests --file pom.xml
      shell: bash

