ALTER TABLE T_BOOKING DROP COLUMN id;
ALTER TABLE T_BOOKING ADD COLUMN id BIGINT;

ALTER TABLE T_BOOKING DROP COLUMN rack_id;
ALTER TABLE T_BOOKING ADD COLUMN rack_id BIGINT;

ALTER TABLE T_BOOKING DROP COLUMN requested_id;
ALTER TABLE T_BOOKING ADD COLUMN requested_id BIGINT;

ALTER TABLE T_RACK DROP COLUMN id;
ALTER TABLE T_RACK ADD COLUMN id BIGINT;

ALTER TABLE T_RACK DROP COLUMN team_id;
ALTER TABLE T_RACK ADD COLUMN team_id BIGINT;

ALTER TABLE T_RACK_ASSET DROP COLUMN id;
ALTER TABLE T_RACK_ASSET ADD COLUMN id BIGINT;

ALTER TABLE T_RACK_ASSET DROP COLUMN rack_id;
ALTER TABLE T_RACK_ASSET ADD COLUMN rack_id BIGINT;

ALTER TABLE T_TEAM DROP COLUMN id;
ALTER TABLE T_TEAM ADD COLUMN id BIGINT;

ALTER TABLE T_TEAM_MEMBER DROP COLUMN id;
ALTER TABLE T_TEAM_MEMBER ADD COLUMN id BIGINT;

ALTER TABLE T_TEAM_MEMBER DROP COLUMN team_id;
ALTER TABLE T_TEAM_MEMBER ADD COLUMN team_id BIGINT;